export const TIPOS_ALERTA = {
  HORAS_EXCEDIDAS: 'HORAS_EXCEDIDAS',
  HORAS_INSUFICIENTES: 'HORAS_INSUFICIENTES',
  AMBIENTE_OCUPADO: 'AMBIENTE_OCUPADO',
  ASIGNACION_PROVISIONAL: 'ASIGNACION_PROVISIONAL',
  INSTRUCTOR_PLANTA_JORNADA_NOCTURNA: 'INSTRUCTOR_PLANTA_JORNADA_NOCTURNA',
} as const;

export type TipoAlerta = (typeof TIPOS_ALERTA)[keyof typeof TIPOS_ALERTA];
